// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::drivetrainVictorLeftA;
std::shared_ptr<SpeedController> RobotMap::drivetrainVictorRightA;
std::shared_ptr<RobotDrive> RobotMap::drivetrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    drivetrainVictorLeftA.reset(new Talon(1));
    lw->AddActuator("Drivetrain", "VictorLeftA", std::static_pointer_cast<Talon>(drivetrainVictorLeftA));
    
    drivetrainVictorRightA.reset(new Talon(2));
    lw->AddActuator("Drivetrain", "VictorRightA", std::static_pointer_cast<Talon>(drivetrainVictorRightA));
    
    drivetrainRobotDrive.reset(new RobotDrive(drivetrainVictorLeftA, drivetrainVictorRightA));
    
    drivetrainRobotDrive->SetSafetyEnabled(false);
        drivetrainRobotDrive->SetExpiration(0.1);
        drivetrainRobotDrive->SetSensitivity(0.5);
        drivetrainRobotDrive->SetMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
